### ISSUE TITLE
btrfs_subvol_usage "Use of uninitialized value in concatenation (.) or string at /etc/munin/plugins/btrfs_subvol_usage line 97."

### ISSUE THREAD

**Issue by ChojinDSL** [munin-monitoring/contrib#1014]
Are there any further requirements to this plugin apart from having BTRFS and quota support enabled on the volume?

Whenever I run the plugin I get the error `"Use of uninitialized value in concatenation (.) or string at /etc/munin/plugins/btrfs_subvol_usage line 97."`
When I run the plugin directly via munin-run I get an output like this:
`Use of uninitialized value in concatenation (.) or string at /etc/munin/plugins/btrfs_subvol_usage line 97`
`1305.value`

 
The resulting graphs in munin show no values.

Have I overlooked something?

**Comment by ChojinDSL** [comment]
Ok, I have one server running Debian Stretch (9.0)
and another one running Debian Buster (10)
On debian stretch it works, on debian buster it doesn't and gives me the aforementioned errors.

Both servers use Kernel 4.19
The Stretch server uses btrfs-progs 4.7.3
The Buster server uses btrfs-progs 4.20.1

**Comment by ChojinDSL** [comment]
Ok, I've found the issue. On my stretch installation I'm using the munin-btrfs-plugin from the backports repo. On the buster install it's from the main repo. Apparently the --raw option was missing in buster.

**Comment by sumpfralle** [comment]
> On my stretch installation I'm using the munin-btrfs-plugin from the backports repo. On the buster install it's from the main repo.

I am slightly confused: I am not aware of this plugin being packaged for Debian. Which package does it belong to?
(`dpkg -S /usr/share/munin/plugins/btrfs_subvol_usage`)

> Apparently the --raw option was missing in buster.

Thus btrf-progs 4.20 (or earlier) stopped supporting this flag? Should we remove/replace it in the plugin?
