### ISSUE TITLE
contrib/plugins/arp/arp is obsolete

### ISSUE THREAD

**Issue by troffasky** [munin-monitoring/contrib#1024]
contrib/plugins/arp/arp is obsoleted by contrib/plugins/arp/arp_  which gives more comprehensive information using the more modern tools [iproute2 etc]. 
Only downside is that it's per-interface rather than global but I'm not sure how useful a global neighbours count is anyway.

**Comment by sumpfralle** [comment]
Another downside is its focus on Linux. But I guess, we cannot have platform compatibility in this field.

I would appreciate a `multigraph` arp plugin for different interfaces. Maybe someone feels encouraged :)

Anyway: I follow your suggestion.
