### ISSUE TITLE
docker plugins fails in CentOS 7, these can not found the counters files 

### ISSUE THREAD

**Issue by paulrm** [munin-monitoring/contrib#1027]
The plugins docker_cpu and docker_memory try retrieve the information from files with this path

Example for docker_cpu

`/sys/fs/cgroup/cpuacct/docker/$id/cpuacct.usage_percpu`

But in CentOS 7 and others linux the path is something like 

`/sys/fs/cgroup/cpuacct/system.slice/docker-$id.scope/cpuacct.usage_percpu`

**Comment by sumpfralle** [comment]
I guess, both path are correct - they probably just represent different ways of starting docker.
The latter looks like a systemd-related path.

It would be great, if you could prepare a pull request, that detects the path to use.
