### ISSUE TITLE
munin-run ssl-certificate-expiry_www.example.com not working

### ISSUE THREAD

**Issue by oz42** [munin-monitoring/contrib#1038]
'munin-run ssl-certificate-expiry_www.example.com' says:
# Unknown service 'ssl-certificate-expiry_www.example.com'

Nothing configured in config file. munin-run --debug does not help here.

OS is FreeBSD 12.1-RELEASE-p1.

**Comment by sumpfralle** [comment]
> Unknown service 'ssl-certificate-expiry_www.example.com'

This means that there is no file `/etc/munin/plugins/ssl-certificate-expiry_www.example.com` (or maybe some other directory - depending on your system).

Did you already create this symlink?

**Comment by oz42** [comment]
The file exists. It turned out that this check had to be adjusted for FreeBSD. Now it is working.
Would it be a good idea to implement a check?

If Linux then...
elif FreeBSD then...

**Comment by sumpfralle** [comment]
> Would it be a good idea to implement a check?

The optimal solution would be a portable test, that just works on both systems.
But if this is not possible, then such a platform-dependent conditional may be suitable.

Could you please describe your local workaround? We will surely find a good way forward ...

**Comment by oz42** [comment]
I have written a patch, now this check works fine on FreeBSD and Linux.

**Comment by oz42** [comment]
Okay, no patch file upload allowed. Well, then:

72c72,78
<             valid_until_epoch=$(date --date="$valid_until_string" +%s)
---
>             case `uname` in
>                 Linux*)    valid_until_epoch=$(date --date="$valid_until_string" +%s)
>                            now_epoch=$(date +%s) ;;
>                 FreeBSD*)  valid_until_epoch=$(date -j -f '%b %e %T %Y %Z' "$valid_until_string" +%s)
>                            now_epoch=$(date -j +%s) ;;
>                 *)         valid_until_epoch=0 ;;
>             esac
74d79
<                 now_epoch=$(date +%s)

**Comment by sumpfralle** [comment]
> Now I have to find out how to attach my patch to this post...

Simply paste it here raw, if you like ...

**Comment by sumpfralle** [comment]
I pushed a fix according to the patch, that you posted before (which is not visible anymore).

See 292cfb955ae6c3c902df73f42f7e5f320f93fc92.

Please test, whether it works for you.

Thank you!

**Comment by oz42** [comment]
Hello,
patch attached.
[ssl-certificate-expiry.diff.txt](https://github.com/munin-monitoring/contrib/files/4116054/ssl-certificate-expiry.diff.txt)

**Comment by sumpfralle** [comment]
Thank you for resending. I think, my commit works well along these lines: 292cfb955ae6c3c902df73f42f7e5f320f93fc92. Please verify, whether it works for you.

**Comment by oz42** [comment]
I think line 97 is wrong. Reason:
date --date="$valid_until_string" +%s
sets the time on FreeBSD. At least this had happened to me once.

**Comment by oz42** [comment]
OK, I have tried the patch. Result on FreeBSD:

# munin-run ssl-certificate-expiry_binky.tuxfriends.net
binky_tuxfriends_net.value U

# munin-run ssl-certificate-expiry
#

**Comment by sumpfralle** [comment]
Is `date` a builtin of you `/bin/sh`? What exactly is your `/bin/sh`?

(I am happy about as much input as possible, since I know almost nothing about the differences of platforms in this regard)

**Comment by oz42** [comment]
I had a typo in the s_client section. This one now works on FreeBSD and Linux and can be customized to other OSes.
[ssl-certificate-expiry.diff.txt](https://github.com/munin-monitoring/contrib/files/4160128/ssl-certificate-expiry.diff.txt)

**Comment by oz42** [comment]
About FreeBSD: /bin/sh is a simple Bourne shell. No builtin commands like in bash.

**Comment by sumpfralle** [comment]
I just pushed commit 52144bc27 - it removes the `-CApath` argument from `s_client`. I guess, this was the point of your change request?

> About FreeBSD: /bin/sh is a simple Bourne shell. No builtin commands like in bash.

I would guess, that `type command` would reveal at least this shell builtin, but I may be wrong ...

Please report back, whether the current state of the plugin in the repository works for you now. Thank you!

**Comment by sumpfralle** [comment]
I guess it works. Otherwise: please report back!
