### ISSUE TITLE
Comment error in postgresql/postgres_queries3_

### ISSUE THREAD

**Issue by rmaziere** [munin-monitoring/contrib#1067]
I think there is an error in a comment for the file : plugins/postgresql/postgres_queries3_ line 15 :
```sh
#    EX: postgres_queries3_table1-table2-table3
```
I think it must be *db* instead *table*.
https://github.com/munin-monitoring/contrib/blob/master/plugins/postgresql/postgres_queries3_#L15

**Comment by sumpfralle** [comment]
Thank you for spotting and reporting this!
