### ISSUE TITLE
qstatus will be deprecated in sabnzbd 3.0.0

### ISSUE THREAD

**Issue by waywit** [munin-monitoring/contrib#1082]
Hi

regarding the following Plugins:
- plugins/sabnzbd/sabnzbd_speed
- plugins/sabnzbd/sabnzbd_dataleft

After updating to sabnzbd 3.0.0 Alpha1 I get Warnings about "qstatus" will be deprecated in upcoming version 3.0:
2020-05-11 19:30:04,684::DEBUG::[interface:444] API-call from XXX.YYY.ZZZ.AAA [Munin_GetXML_sabnzbd_speed libwww-perl/6.43] {'mode': 'qstatus', 'output': 'xml', 'apikey': '********************'}
2020-05-11 19:30:04,684::WARNING::[api:149] The API-method 'qstatus' is deprecated and will be removed in the final version of 3.0.0.

I think the function will be completely removed, details can be found here: https://sabnzbd.org/wiki/advanced/api

It would be nice to switch the plugin to the "normal" status function.

Thanks and best regards!

**Comment by waywit** [comment]
Just checked the two plugins and replaced 
`"my $URL = $HOST."/sabnzbd/api?mode=qstatus&output=xml&apikey=".$API;"`
with
`"my $URL = $HOST."/sabnzbd/api?mode=queue&output=xml&apikey=".$API;"`

And it look good... no more warnings and the graphs looking also good... should be a small fix ;-)

Thanks and best regards!

**Comment by sumpfralle** [comment]
Thanks for providing the necessary code change!

Would this change break compatibility with older versions of `sabnzbd`? It would be nice, if the plugins worked for both older and newer ones (but it is not strictly necessary, if hard to achieve).

**Comment by waywit** [comment]
Hi, for me it looks like that the "queue" parameter exists in versions older than 2.0.0, because in the API description there are changes from older version to 2.0.0 described: https://sabnzbd.org/wiki/advanced/api#queue
But this is just a assumption, I du not exactly know what was in the SABnzbd API in older versions...

**Comment by sumpfralle** [comment]
Thank you for verifying the compatibility.
