### ISSUE TITLE
unifi_api: Error for use of uninitialized values

### ISSUE THREAD

**Issue by kboenke** [munin-monitoring/contrib#1095]
Running `unifi_api` generally works, but produces some errors during each run:
> me@host:/etc/munin# /usr/sbin/munin-run unifi_api
> Use of uninitialized value in addition (+) at /etc/munin/plugins/unifi_api line 1036.

Values are generated as expected. `errors` are not reported, likely due to this error. I am not familiar with the structure of the JSON being processed, but looking at the code it might be as easy as assuming 0 values if the return-value is empty:
> 'err'   => ($_->{$name . '-rx_errors'} **|| 0**) + ($_->{$name . '-tx_errors'} **|| 0**),

@jtsage can likely assess this easily.

**Comment by sumpfralle** [comment]
Thanks for your proposal.

I assume, this is the proper way of dealing with the response.

@jtsage: feel free to re-open, if you see a better way.

**Comment by jtsage** [comment]
oh, sweet.  @kboenke didn't realize you had already done a pull request, was trying to find time to come visit this.  Works for me, thanks!!

~j
