### ISSUE TITLE
potential bug in disk -> nvme -> nvme_writecycles

### ISSUE THREAD

**Issue by wadabum** [munin-monitoring/contrib#1127]
The graph [nvme_**write**cycles](https://github.com/munin-monitoring/contrib/blob/master/plugins/disk/nvme#L265) uses the value of [data_units_**read**](https://github.com/munin-monitoring/contrib/blob/master/plugins/disk/nvme#L270)

I wonder if this should be `data_units_written` instead?
As to my (googled) understanding [destructive read](https://en.wikipedia.org/wiki/Memory_refresh) is not a thing on drives

fyi @kjetilho

**Comment by steveschnepp** [comment]
👍 to me

**Comment by kjetilho** [comment]
:facepalm:

**Comment by sumpfralle** [comment]
closed by #1132
