### ISSUE TITLE
munin-cron does not generate image for nvme plugin read/write bytes

### ISSUE THREAD

**Issue by solsticedhiver** [munin-monitoring/contrib#1167]
I installed the **nvme** plugin and configure it to run.

I got the graph for *writecycles* or *usage* generated automatically by `munin-cron`
But even though there is a `nvme_bytes.html` generated there is no `nvme_bytes-day.png` generated ever. Or `nvme_bytes-week.png`, either.

There is a broken image link in the index page of the host in question.

**Comment by sumpfralle** [comment]
I guess, that you can find some kind of error messages in `/var/log/munin/munin-cgi-graph.log`?

Does `munin-run nvme` (or `nvme_bytes`?) emit reasonable output?

**Comment by solsticedhiver** [comment]
Well, I don't have a `/var/log/munin/munin-cgi-graph.log` but a `/var/log/munin/munin-graph.log`

What is standing out is the error:

    2021/01/24 00:02:02 [RRD ERROR] Unable to graph /srv/http/munin/rhea/rhea/nvme_bytes-year.png : undefined vname cXXXXXXXXXXXXXXX_r

The complete output is:

    2021/01/24 00:02:02 [RRD ERROR] rrdtool 'graph' '/srv/http/munin/rhea/rhea/nvme_bytes-year.png' \
            '--title' \
            'NVME Bytes Read / Written - by year' \
            '--start' \
            '-400d' \
            '--vertical-label' \
            'bytes read (-) / written (+) per second'' \
            '--slope-mode' \
            '--height' \
            '175' \
            '--width' \
            '400' \
            '--imgformat' \
            'PNG' \
            '--lazy' \
            '--font' \
            'DEFAULT:0:DejaVuSans,DejaVu Sans,DejaVu LGC Sans,Bitstream Vera Sans' \
            '--font' \
            'LEGEND:7:DejaVuSansMono,DejaVu Sans Mono,DejaVu LGC Sans Mono,Bitstream Vera Sans Mono,monospace' \
            '--color' \
            'BACK#F0F0F0' \
            '--color' \
            'FRAME#F0F0F0' \
            '--color' \
            'CANVAS#FFFFFF' \
            '--color' \
            'FONT#666666' \
            '--color' \
            'AXIS#CFD6F8' \
            '--color' \
            'ARROW#CFD6F8' \
            '--border' \
            '0' \
            '-W' \
            'Munin 2.0.66' \
            'DEF:a6c34d9d63098c24=/var/lib/munin/rhea/rhea-nvme_bytes-_XXXXXXXXXXXXXX_w-d.rrd:42:MAX' \
            'DEF:i6c34d9d63098c24=/var/lib/munin/rhea/rhea-nvme_bytes-_XXXXXXXXXXXXXX_w-d.rrd:42:MIN' \
            'DEF:g6c34d9d63098c24=/var/lib/munin/rhea/rhea-nvme_bytes-_XXXXXXXXXXXXXX_w-d.rrd:42:AVERAGE' \
            'DEF:ad4442274191328a=/var/lib/munin/rhea/rhea-nvme_bytes-_XXXXXXXXXXXXXX_r-d.rrd:42:MAX' \
            'DEF:id4442274191328a=/var/lib/munin/rhea/rhea-nvme_bytes-_XXXXXXXXXXXXXX_r-d.rrd:42:MIN' \
            'DEF:gd4442274191328a=/var/lib/munin/rhea/rhea-nvme_bytes-_XXXXXXXXXXXXXX_r-d.rrd:42:AVERAGE' \
            'CDEF:cd4442274191328a=gd4442274191328a,POP,UNKN' \
            'CDEF:c6c34d9d63098c24=g6c34d9d63098c24,POP,UNKN' \
            'COMMENT:            ' \
            'COMMENT:Cur (-/+)' \
            'COMMENT:Min (-/+)' \
            'COMMENT:Avg (-/+)' \
            'COMMENT:Max (-/+) \j' \
            'LINE1:g6c34d9d63098c24#00CC00:/dev/nvme0n1 ' \
            'GPRINT:cXXXXXXXXXXXXXXX_r:LAST:%6.2lf%s/\g' \
            'GPRINT:c6c34d9d63098c24:LAST:%6.2lf%s' \
            'GPRINT:iXXXXXXXXXXXXXXX_r:MIN:%6.2lf%s/\g' \
            'GPRINT:i6c34d9d63098c24:MIN:%6.2lf%s' \
            'GPRINT:gXXXXXXXXXXXXXXX_r:AVERAGE:%6.2lf%s/\g' \
            'GPRINT:g6c34d9d63098c24:AVERAGE:%6.2lf%s' \
            'GPRINT:aXXXXXXXXXXXXXXX_r:MAX:%6.2lf%s/\g' \
            'GPRINT:a6c34d9d63098c24:MAX:%6.2lf%s\j' \
            'CDEF:re_zero=gXXXXXXXXXXXXXXX_r,UN,0,0,IF' \
            'CDEF:ngXXXXXXXXXXXXXXX_r=gXXXXXXXXXXXXXXX_r,-1,*' \
            'LINE1:ngXXXXXXXXXXXXXXX_r#00CC00' \
            'LINE1:re_zero#000000' \
            'VRULE:1611441306#999999' \
            'COMMENT:Last update\: Sat Jan 23 23\:35\:06 2021\r' \
            '--end' \
            '1611360000'
    


But `munin-run nvme` on the host, gives:

    multigraph nvme_usage
    XXXXXXXXXXXXXXX.value 61.9291370071183
    multigraph nvme_bytes
    XXXXXXXXXXXXXXX_r.value 853387
    XXXXXXXXXXXXXXX_w.value 683796
    multigraph nvme_writecycles
    XXXXXXXXXXXXXXX.value 1.40007818923458

**Comment by solsticedhiver** [comment]
ok. this works fine in munin 2.0.67

**Comment by sumpfralle** [comment]
Thank you for verifying the fix!
