### ISSUE TITLE
docker_ plugins say 'containers' serie is not supported but it seems it is

### ISSUE THREAD

**Issue by rsanzante** [munin-monitoring/contrib#1180]
docker_ plugin comments say:

```
This wildcard plugin provides series C<containers>, C<images>, C<status>,
C<volumes>, C<cpu>, C<memory> and C<network> as separate graphs. It also
supports a C<multi> suffix that provides all of those as a multigraph.
```

However, if you create a plugin symlink to the docker_ file called docker_containers when munin tries to execute it the response is:

```
munin-run docker_containers
# Unknown service 'docker_containers'
```

Checking the code it seems the 'containers' series is missing when checking for valid series:
```
    series = [
        'cpu',
        'images',
        'memory',
        'network',
        'status',
        'volumes',
    ]
```

Adding 'containers' to that variable result in a valid plugin execution:
```
munin-run docker_containers
containers_quantity.value 1
```

**Comment by rsanzante** [comment]
PR added: https://github.com/munin-monitoring/contrib/pull/1181

**Comment by sumpfralle** [comment]
Thanks for providing the fix for this!
