### ISSUE TITLE
docker_ plugin: disparity of sanitized container names results in missing data

### ISSUE THREAD

**Issue by dneuge** [munin-monitoring/contrib#1212]
`docker_` plugin sanitizes container names through `clean_fieldname` in configuration but not when dumping actual values; for example dots (`.`) are being replaced by underscores (`_`). This leads to a disparity which affects `cpu`, `memory` and `network` graphs. Graphs will only show `-nan` instead of a value for affected containers.

### Example
For a container name `my.container` configuration will announce keys containing `my_container` although values are still printed as `my.container`.

**Comment by sumpfralle** [comment]
fixed in #1213, thanks!
