### ISSUE TITLE
RSS Feed not working

### ISSUE THREAD

**Issue by quotengrote** [munin-monitoring/contrib#1283]
Hi,

the RSS-Feed on https://gallery.munin-monitoring.org is not working and redirects to "https://gallery.munin-monitoring.org//.Permalink".

Wishes
mg

**Comment by sumpfralle** [comment]
Thanks for your bug report!
I fixed this now.

**Comment by sumpfralle** [comment]
Just for the reference: the fix is in the [munin-plugin-gallery repository](https://github.com/munin-monitoring/munin-plugin-gallery/commit/a75eff33dccb64fbd1d7b4df9fe1e4ff8bbdbc86).
