### ISSUE TITLE
feature: snmp__if_multi templates and ignoreOper

### ISSUE THREAD

**Issue by Mrten** [munin-monitoring/contrib#432]
same as munin-monitoring.org/trac ticket 1431:

http://munin-monitoring.org/attachment/ticket/1431/snmp__if_multi.patch

This patch adds two new features to snmp__if_multi:

 * env.ignoreOper
 * env.template

 env.ignoreOper is for switches that always display 'down' in ifOperStatus,
 ifAdminStatus is used (netgear FVS336G is what I wrote this for)

 env.template is a template for the name of the graph that allows you
 Template::Tiny style formatting for the graph_title of the plugin. The
 default didn't suit me (netgear GS108 is what I wrote this for), the names
 of the interfaces I set in the webinterface never showed up in the graph.

 This makes snmp_if_multi depend on Template::Tiny, but this may be
 alleviated: the template engine is only used for the graph_title if you
 set the environment variable but I really do not know how to include
 ('use') conditionally in Perl.

Which one is active? the trac or this github?

**Comment by ssm** [comment]
The plugin this ticket refers to is in the https://github.com/munin-monitoring/munin repository.

The patch no longer applies cleanly to the plugin in the "munin" repo, and it introduces new dependencies.

If you can, please submit the new plugin as a pull request to the "contrib" repository, and it will be easy to include it.  If it did not depend on Template::Tiny, it would be easier to update the plugin tin the "munin" repo.
