### ISSUE TITLE
plugin/time/chrony throws errors

### ISSUE THREAD

**Issue by Farom** [munin-monitoring/contrib#446]
root@host:~# munin-run chrony
systime.value 0.70
frequency.value -0.00
residualfreq.value 0.35
skew.value 1978.40
rootdelay.value -7.00
rootdispersion.value 357.00
.value (standard_in) 2: syntax error
0.00
.value (standard_in) 2: syntax error
0.00
.value (standard_in) 2: syntax error
0.00
.value (standard_in) 1: illegal character: N
(standard_in) 2: syntax error
0.00

''chronyc tracking'' gives more lines, than fields and fieldnames are defined, so for the last lines:
''
Update interval : 258.8 seconds
Leap status     : Normal
''
there is no field left.

**Comment by sumpfralle** [comment]
Is this issue still open? What should be done?

**Comment by Farom** [comment]
Yes this is still open and it is still broken.
```bash
root@gizmo:~# munin-run chrony 
stratum.value  3
systime.value  -0.000126
frequency.value  0.00021326
residualfreq.value  0.021326
skew.value  -555.5
rootdelay.value  7577
rootdispersion.value  1000000000
.value  0
.value  0
.value  0
.value  0
```
the script calls 'chronyc tracking'
this gives output (with chrony 2.4):
```bash
# chronyc tracking
Reference ID    : 212.224.120.164 (ntp.5zs.de)
Stratum         : 3
Ref time (UTC)  : Thu Nov 10 08:20:27 2016
System time     : 0.000000128 seconds slow of NTP time
Last offset     : +0.000213260 seconds
RMS offset      : 0.000213260 seconds
Frequency       : 5.555 ppm slow
Residual freq   : +7.577 ppm
Skew            : 1000000.000 ppm
Root delay      : 0.055859 seconds
Root dispersion : 167.248688 seconds
Update interval : 1.9 seconds
Leap status     : Normal
```
Then some awk magic happens, that creates broken lines (`.value  0`), if the field does not exists in $fieldnames.
This awk magic has a comment:
`# remove non-needed output lines,[…]`
but it does not do this.

You have to correct the awk script to really throw away non-needed lines.

**Comment by sumpfralle** [comment]
I rewrote the plugin since the field handling was hard to maintain.
Please verify if it is working for you: #769

**Comment by sumpfralle** [comment]
@Farom: could you test my merge request, please?

**Comment by Farom** [comment]
@sumpfralle it gives data and your code looks much more maintainable than the old script. So thanks.

But the values are different:

```
# munin-run  chrony ; echo ------------------; munin-run shiny-new-chrony ; echo ---------------------;  chronyc tracking
frequency.value  0.000209528
residualfreq.value  0.114755
skew.value  -1497.6
rootdelay.value  15
rootdispersion.value  257
------------------
frequency.value -14.976
residualfreq.value 1.5
skew.value 25.7
rootdelay.value 246.81
rootdispersion.value 1.886
---------------------
Reference ID    : 76.127.35.142 (a.st1.ntp.br)
Ref time (UTC)  : Wed Dec  7 10:20:10 2016
Last offset     : +0.000209528 seconds
RMS offset      : 0.001147552 seconds
Frequency       : 14.976 ppm slow
Residual freq   : +0.015 ppm
Skew            : 0.257 ppm
Root delay      : 0.246810 seconds
Root dispersion : 0.001886 seconds
Update interval : 517.2 seconds
Leap status     : Normal
```

(I have deleted the lines, that are equal in all ouputs).

Your new version gives correct values. The old one is buggy.


Thanks a lot!
@steveschnepp  please pull

**Comment by sumpfralle** [comment]
The changed values are a bit surprising for me. Anyway, I will merge. Thank you for your test!
