### ISSUE TITLE
contrib/plugins /network/avm-fritzbox-wan-traffic - "File not found at /usr/share/perl5/Munin/Node/Service.pm line 263, <STDIN> line 18."

### ISSUE THREAD

**Issue by seegras3** [munin-monitoring/contrib#516]
When trying to load the Plugin, i'm getting this Error Message

2014/08/17-16:55:05 [7718]      Can't exec "/etc/munin/plugins/fritz_traffic": Datei oder Verzeichnis nicht gefunden at /usr/share/perl5/Munin/Node/Service.pm line 263, <STDIN>            line 17.
2014/08/17-16:55:05 [7718] Service 'fritz_traffic' exited with status 42/0.

The requested file exists; What can I do as a solution

**Comment by syswombat** [comment]
short description what i have done, and what is wrong
http://www.wombat.ch/index.php?option=com_content&view=article&id=9484:munin-node-avm-fritzbox-monitoren&catid=64:munin&Itemid=101

**Comment by ssm** [comment]
note: wombat.ch is no longer available, so the link above is dead.

**Comment by sumpfralle** [comment]
The error message above was caused by a missing  interpreter (here: php).
Since the munin plugin never gains control in these situations, we cannot detect this problem and do something about it. Thus I would consider it an configuration error instead of a plugin bug.
