### ISSUE TITLE
Switching from ps to top causes problems with usernames > 8 chars in cpubyuser

### ISSUE THREAD

**Issue by CoRpO** [munin-monitoring/contrib#520]
Commit d824c7696f510011dc6524002d8455133fb99b90 broke cpubyuser for usernames > 8 chars

**Comment by sumpfralle** [comment]
Fixed in 78f4e42d21958963ad893742110a16a292b97ecb and 8280dbb0f5050b077453947daa60dc5d3ca39b60.
