### ISSUE TITLE
Modern template

### ISSUE THREAD

**Issue by szepeviktor** [munin-monitoring/contrib#554]
Please consider adding/adding as a git submodule this template:
https://github.com/jonnymccullagh/munstrap

**Comment by 6temes** [comment]
I think that should substitute the official templates.

**Comment by timss** [comment]
In that case the icons should atleast be changed back to the original ones.

**Comment by jonnymccullagh** [comment]
timss, Can I just confirm. By icons do you mean the main munin logo? I can't see any other icons in the standard munin template. Cheers, jonny

**Comment by timss** [comment]
@jonnymccullagh All of the icons resided inside [`../static/img/`](https://github.com/jonnymccullagh/munstrap/tree/master/static/img) in your template. 

What I think of these icons personally is not particularly interesting, but if it were to become the official or an alterantive template I think the official current icons should be used instead as they're easy to recognize and carries "historic significance". For reference this is the original logo:

![munin logo](http://munin-monitoring.org/site/munin.png)

That being said I think your template is great :)

**Comment by steveschnepp** [comment]
@timss Note that there is already a new CSS on the devel version of munin, as shown in http://demo.munin-monitoring.org/. 

Although I also agree that @jonnymccullagh templates are great, I'm still reluctant to change the default layout of our html pages (I was quite eager to some while ago).

A nice way would be to make it *very* easy to change the templates. A specialized, extra, distribution package that uses a sort of alternative mechanism comes to my mind.

**Comment by timss** [comment]
@steveschnepp Oh cool, thanks for pointing me to that. Looks promising. A more streamlined install of alternative templates would be nice too.

**Comment by szepeviktor** [comment]
I miss (plugin) navigation from munin's current templates.
Once you click something on top the menu scrolls out of the viewport.

**Comment by jonnymccullagh** [comment]
@timss I have reverted to the official logo here https://github.com/jonnymccullagh/munstrap 
@steveschnepp I agree a template switching mechanism would be great. My aim was to modernise the look but without ever touching (breaking) the core Munin code. 

Now, could someone point me in the right direction to add munstrap to munin-monitoring/contrib - my git foo is lacking. Do I ask to be added to contrib as a user? Or should I fork and then create a pull request? Any help is appreciated.

**Comment by frdmn** [comment]
@jonnymccullagh Usually, you just fork this (contrib) repository, make your changes, and send a PR that gets reviewed and potentially merged into this repository again.

**Comment by jonnymccullagh** [comment]
Thanks @frdmn I think I have done that now, but happy to amend if I have done anything wrong.

**Comment by steveschnepp** [comment]
@jonnymccullagh I just merged #591.

**Comment by szepeviktor** [comment]
Thank you!
