### ISSUE TITLE
monit_parser should you monit's XML output

### ISSUE THREAD

**Issue by szepeviktor** [munin-monitoring/contrib#558]
monit outputs MB, GB beside kB
https://github.com/munin-monitoring/contrib/blob/master/plugins/monit/monit_parser#L43
Please convert SI prefixes.
```
Process 'php5-fpm-unix'
  status                            Running
  monitoring status                 Monitored
  pid                               9693
  parent pid                        1
  uid                               0
  effective uid                     0
  gid                               0
  uptime                            1d 11h 30m
  children                          41
  memory kilobytes                  7.9 MB
  memory kilobytes total            1.1 GB  <---------------------
  memory percent                    0.3%
  memory percent total              57.0%
  cpu percent                       0.0%
  cpu percent total                 1.3%
  unix socket response time         0.000s to /var/run/php5-fpm-olm.sock [DEFAULT]
  data collected                    Fri, 19 Dec 2014 11:11:47
```

**Comment by ssm** [comment]
Do you have an example of the xml output format from monit?

**Comment by szepeviktor** [comment]
This is my current status: https://gist.github.com/szepeviktor/7acc8e9bf48bba41819a

**Comment by szepeviktor** [comment]
Try pasting it here: http://xmlgrid.net/

**Comment by ssm** [comment]
Viktor Szépe <notifications@github.com> writes:

> This is my current status: https://gist.github.com/szepeviktor/7acc8e9bf48bba41819a


Thanks. Output on a structured format is easier to work with, even if it
is XML. :)

Note to self: Need to read the monit source to see if the kilobyte and
kilobytetotal fields are binary or decimal.

-- 
Stig Sandbeck Mathisen

**Comment by szepeviktor** [comment]
variables:
https://bitbucket.org/tildeslash/monit/src/fe1f98628ca6b9f83420b01c08a4239b11738727/src/xml.c?at=master#cl-327
data types:
https://bitbucket.org/tildeslash/monit/src/fe1f98628ca6b9f83420b01c08a4239b11738727/src/monit.h?at=master#cl-506

**Comment by szepeviktor** [comment]
Smal parsing example
```python
#!/usr/bin/python

import xml.etree.ElementTree as ET

monit = ET.parse('monit-status.xml')

services = monit.findall(".//memory/kilobytetotal/../..")

for service in services:
  print service.find("name").text, service.find("memory/kilobytetotal").text
```

**Comment by szepeviktor** [comment]
Hacky solution for now:
```python
    m = re.match("  memory total\s+([0-9.]+) ([kMG])B$", line)
    if m:
        prefix = m.group(2)
        multi = 1
        if prefix == 'M':
            multi = 1024
        elif prefix == 'G':
            multi == 1048576
        procs[cur_proc]["total_memory"] = float(m.group(1))*multi
        continue
```

**Comment by sumpfralle** [comment]
Could you turn this into a pull request? Or maybe the problem is already fixed?

**Comment by szepeviktor** [comment]
Now monit's output looks like:
```
memory                       0.0% [812 kB]
memory total                 0.0% [812 kB]
```

The author suggested we should parse the XML output (seea above)

**Comment by sumpfralle** [comment]
@szepeviktor: how about [this](https://github.com/sumpfralle/contrib/commit/ef6cedf7a918199ea960f9a96395fa4fda1111ce) one?
It requires Python3 an parses the XML data.

**Comment by szepeviktor** [comment]
OK!
