### ISSUE TITLE
zpool_iostat Permission denied

### ISSUE THREAD

**Issue by theking2** [munin-monitoring/contrib#560]
# munin-run zpool_iostat
Unable to open /dev/zfs: Permission denied.
Unable to open /dev/zfs: Permission denied.
_read.value _write.value rm: cannot remove '/var/run/munin/zpool_iostat': Permission denied

**Comment by ssm** [comment]
The plugin needs to run as root.  Please add configuration in /etc/munin/plugin-conf.d/zfs.conf to that effect.  Something like:

    [zpool_*]
    user root

…should do the trick
