### ISSUE TITLE
Varnish 4.0.3-1 errors

### ISSUE THREAD

**Issue by sokai** [munin-monitoring/contrib#588]
Hi there,

since the last Varnish update (from ```4.0.2-1``` to ```4.0.3-1```) on Ubuntu 12.04.5 with the [official PPA](https://repo.varnish-cache.org/ubuntu/) enabled I get some errer messages with the [Munin plugin hosted here](https://github.com/munin-monitoring/contrib/tree/master/plugins/varnish4).

```
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_bad.SMA_ransient_c_fail.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_memory_usage.SMA_ransient_c_bytes.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_memory_usage.SMA_ransient_g_bytes.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_memory_usage.SMA_Transient_g_space.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_bad.SMA_ransient_c_fail.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_memory_usage.SMA_ransient_c_bytes.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_memory_usage.SMA_ransient_g_bytes.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_memory_usage.SMA_Transient_g_space.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_bad.SMA_ransient_c_fail.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_memory_usage.SMA_ransient_c_bytes.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_memory_usage.SMA_ransient_g_bytes.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_memory_usage.SMA_Transient_g_space.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339._space.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
```

After disabling ```varnish_memory_usage``` I only get three lines in the error message:
```
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_bad.SMA_ransient_c_fail.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_bad.SMA_ransient_c_fail.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
Malformed configuration line "DOMAIN;HOST.DOMAIN:varnish_bad.SMA_ransient_c_fail.label". at /usr/share/perl5/Munin/Master/Utils.pm line 339.
```
→ **Is there someone (maybe @ioppermann or @KristianLyng) who can help me?** – I have no clue how to fix this … :-/

Thanks a lot and best regards!

**Comment by ioppermann** [comment]
This looks like a configration bug of the Ubuntu installation or in the munin plugins.conf. For example it says `varnish_bad.SMA_ransient_c_fail.label` where the "T" of the word "Transient" is missing. There is no such typo in the varnish4_ module.

Also `DOMAIN;HOST.DOMAIN` should be probably replaced with the actual host name.

**Comment by sokai** [comment]
@ioppermann Thanks a lot for your investigation!

1. `plugins.conf` – I have not such a file. Where can I find it and apply your hint? (I recursively searched in `/etc/munin` , `/usr/share/munin` and `/usr/share/perl5/Munin` for `ransient` and only found `Transient` in the `varnish4_` file …)
2. `DOMAIN;HOST.DOMAIN` – well , yes! – I have configured it correct, but changed it for reporting here …

**Comment by chrisj** [comment]
I have the same bug, I have seen:
ransient
ansient
nsient
sient

I am using the same version of Ubuntu/Varnish
Also I think for me, `plugins.conf` is `/etc/munin/plugin-conf.d/munin-node`

**Comment by sumpfralle** [comment]
Is this still an issue?

**Comment by sokai** [comment]
@sumpfralle Thanks for the reminder! – I cannot find the original posted error messages in my logs, ATM.
So I think this isn't an issue anymore … → *closed*
