### ISSUE TITLE
tc-trampolinessize: Use of uninitialized value in printf at /etc/munin/plugins/hhvm_127.0.0.1_8080 line 119.

### ISSUE THREAD

**Issue by dorogarcia** [munin-monitoring/contrib#610]
Hello,

Last version of hhvm removed 'tc-trampolinessize.value'

# hhvm --version
HipHop VM 3.6.1 (rel)
Compiler: tags/HHVM-3.6.1-0-gc051feff88ba8050f33f10f7b1fb07f8d3415f9e
Repo schema: 42f49251b5c27daf4e13cb6bcd0c7ef4824b55a3
# curl 'http://127.0.0.1:8081/check-health'
{
 "load":1
, "queued":0
, "hhbc-roarena-capac":0
, "tc-hotsize":0
, "tc-size":3622944
, "tc-profsize":4171793
, "tc-coldsize":1730825
, "tc-frozensize":4790415
, "targetcache":174688
, "rds":174688
, "units":858
, "funcs":16889
}
#

If you comment line 119, you will remove warning message:

    printf( "tc-coldsize.value %d\n", $health->{'tc-coldsize'} );
    #printf( "tc-trampolinessize.value %d\n", $health->{'tc-trampolinessize'} );
    printf( "tc-frozensize.value %d\n", $health->{'tc-frozensize'} );

**Comment by sumpfralle** [comment]
fixed in b1f8b9f03e8860b5325e2cccaf9ad4f22bde0295
