### ISSUE TITLE
git submodules allowed?

### ISSUE THREAD

**Issue by MatthiasLohr** [munin-monitoring/contrib#657]
Hey there,

i've a collection of munin plugins for monitoring [GitLab](http://about.gitlab.com) in an own repository (https://github.com/MatthiasLohr/munin-plugins-gitlab). I would like to integrate these plugins in this project, but - to avoid redundancy - would suggest to use git submodule for that. Is that a accepted way?

Best regards
Matthias

**Comment by sumpfralle** [comment]
I understand the munin-contrib repository to be a collection of plugins (and other contributed material) that is maintained by the munin community (resp. the maintainers of this repository). The included plugins and templates (should) have a certain quality and style.

git submodules cannot be directly maintained by the munin community and their quality is outside of its control.

Maybe someone (external) would like to curate a comprehensive "directory" of munin plugins.
This would be a good use-case for git submodules. But I think, this imaginary directory and the current munin contrib repository would try to solve very different problems.
