### ISSUE TITLE
dovecot/dovecot plugin and dovecot log files

### ISSUE THREAD

**Issue by shurale** [munin-monitoring/contrib#689]
This plugin filter log files by "dovecot" substring. It's correct for common log files like /var/log/mail.log. But at my server Dovecot has its own log file without this tag. Please, add option for analysing dovecot-only log files

**Comment by sumpfralle** [comment]
This bug was fixed by your commit e5260be4364e4700c0584dd45a48b5f17ac6a48a, or?

**Comment by sumpfralle** [comment]
Assuming it is fixed.
