### ISSUE TITLE
asterisk: voicemail count is always 0

### ISSUE THREAD

**Issue by lelutin** [munin-monitoring/contrib#697]
Hi there, I'm testing out the asterisk plugin with asterisk 1.8 on debian wheezy.

I'm seeing the total voicemail count as always being 0. I found out that the regexp used for splitting lines on line 274 of the plugin does not match and thus lines are not split correctly.

If I change the regexp to have both \r\n and \n as possible split expressions, it starts accumulating messages and shows the correct total (first line only is changed, the rest is just for context):

```
274   foreach my $line (split(/\r\n|\n/, $voicemail_response)) {
275     next unless $line =~ / ([0-9]+)$/;
276     $messages += $1;
277   }
```

**Comment by sumpfralle** [comment]
Thank you!
fixed in [04def756bc906ebb22cb55f64fbf3ea31f943372]
