### ISSUE TITLE
asterisk: config for voicemail sets up wrong field name

### ISSUE THREAD

**Issue by lelutin** [munin-monitoring/contrib#700]
Hi again, sorry for the deluge of bug reports on the asterisk plugin, but it is ... buggy.

The "config" action for the asterisk_voicemail graph is not setting up the label for the right field name. This created a field called "Total messages" that always value of NaN and the actual value is shown with label "No .label value set". This is because the "config" action sets up a field named "messages" while the accounting code prints out a value for a field named "total".

Simple fix: set the label on the right field name. This change is on current master (only one line changed so I didn't bother making a patch, sorry):

```
177 total.label Total messages
```

**Comment by sumpfralle** [comment]
thank you for spotting this!
