### ISSUE TITLE
Traffic per interface plugin

### ISSUE THREAD

**Issue by eLBati** [munin-monitoring/contrib#716]
Hello,

at [demo.munin-monitoring.org/traffic.html](http://demo.munin-monitoring.org/munin-monitoring.org/demo.munin-monitoring.org/traffic.html) I can see a graph with **bytes/sec** per interface.

If I install [traffic plugin](https://github.com/munin-monitoring/contrib/blob/master/plugins/network/traffic) I can see **bits per second** by IP protocol

Where can I find the traffic plugin used on demo server?

Thanks

**Comment by sumpfralle** [comment]
This is probably the core plugin [ip_](https://github.com/munin-monitoring/munin/blob/master/plugins/node.d.linux/ip_) - at least the html source of the demo site indicates this.
But it seems like this plugin switched from bytes/second to bits/second.
