### ISSUE TITLE
cpubyuser max leght name

### ISSUE THREAD

**Issue by Antenagora** [munin-monitoring/contrib#757]
i've installed this plugin to monitor user load on a server, and for the users with a long name i get some errors, munin-run cpubyuser  reports the folowing values:

sferrar+.value 0
mbabbuc+.value 0
lcarraro.value 0
it doesn't  print the graph.

And in munin server the munin-update.log reports this

2016/10/21 13:15:06 [WARNING] Service cpubyuser on XX returned no data for label sferraresso
2016/10/21 13:15:06 [WARNING] Service cpubyuser on XX returned no data for label mbabbucci

All the users with a shorter name are ok. Could you please give me some help on solving this ?
thanks

**Comment by sumpfralle** [comment]
The plugin uses "top" which abbreviates long usernames.
This is fixed now.

**Comment by Antenagora** [comment]
Testing right now and seems to work, thank you for fixing !
