### ISSUE TITLE
zpool_iostat [Not a valid vname]

### ISSUE THREAD

**Issue by Rayzilt** [munin-monitoring/contrib#779]
Hi,

Not sure if some miss configuration on my side.
I'm trying to get the zfs/zpool_iostat plugin working but munin reports at munin-cgi-graph.log -> " Not a valid vname: c35000cca03b09c640_read in line GPRINT:c35000cca03b09c640_read:LAST:%6.2lf/\g"

Could this be a bug? Or am I completely missing something..

Please find attached all the logging I could find:
[munin-cgi-graph.txt](https://github.com/munin-monitoring/contrib/files/628152/munin-cgi-graph.txt)
[zpool_iostat_config-output.txt](https://github.com/munin-monitoring/contrib/files/628151/zpool_iostat_config-output.txt)
[zpool_iostat-output.txt](https://github.com/munin-monitoring/contrib/files/628153/zpool_iostat-output.txt)

Munin version: 2.0.25 (Debian Jessie Repo)

**Comment by sumpfralle** [comment]
Thank you for your report!
I think, i identified the cause: the pool names start with a digit and the plugin does not handle this properly.

I reworked the zpool_iostat plugin(#781). Please verify that it works for you.
I do not use ZFS - thus I could not test it.

Since you are a user of this plugin: please attach a day and maybe a week graph of this plugin to this bug report (or my merge request), if you can. I would like to add these to the repository for the [Plugin Gallery](http://munin-monitoring.org/wiki/PluginGallery).

**Comment by Rayzilt** [comment]
Thanks for looking in to it!

The numbers are the disks, not the pool name. The poolname in this example is 'pool01'
I will test your changes later today and post result. And you can have a screenshot of the graph.

**Comment by sumpfralle** [comment]
Quick reminder: is it working?

**Comment by Rayzilt** [comment]
Yes! Thanks for the reminder.

Find attached a screenshot of a weekly graph
![screen shot 2016-12-27 at 09 22 09](https://cloud.githubusercontent.com/assets/3105311/21495183/509fafe0-cc16-11e6-80ba-0d4a5daceab9.png)

I will upload one again without the missing piece next week.

**Comment by sumpfralle** [comment]
This is good to hear!

I have some zfs questions for you - just to make sure, that I do not cause misunderstandings for future readers of the code:
* what is the output of `zpool iostat -v` (disks? pools?)
* is there a difference to `zpool iostat -v 1 1`?
* in your example graph there are pools (e.g. "pool01") and disks mixed together? Is this the expected result?

(I was just blindly improving the shell code of the plugin - maybe I misunderstood some parts of the previously little-documented plugin code)

Regarding the example graph: please do not take a screenshot, but just download the image. The above feels a bit blurry.
Take your time - no need to hurry :)

**Comment by Rayzilt** [comment]
zpool iostat -v contains all pools and disks, see attached pdf for a example. The number after -v is: display every # second(s) a new stat. If you only want to see stats of a pool, then zpool iostat [poolname] -v 1 will do.

The mix part is the expected result.

Please find also attached two png files.

Thank you for you time also ;-)

![zpool_iostat-month](https://cloud.githubusercontent.com/assets/3105311/21829699/051431d0-d798-11e6-960f-8c22845abfeb.png)
![zpool_iostat-week](https://cloud.githubusercontent.com/assets/3105311/21829698/05107c84-d798-11e6-94e3-985880e04f3d.png)
[zpool-iostat-v.pdf](https://github.com/munin-monitoring/contrib/files/697678/zpool-iostat-v.pdf)

**Comment by sumpfralle** [comment]
Thank you for providing the details and the graphs.
I renamed some variables (better reflecting their purpose).
Additionally I reverted my inadvertent fieldname change (some commits ago). Now all previous fieldnames (except for the ones with a leading digit) will remain unchanged.

Please test the current state once more.

**Comment by sumpfralle** [comment]
Can you confirm that the current state of my merge request is working for you?

**Comment by sumpfralle** [comment]
This is your last chance for voicing objections regarding the latest state of this plugin :)

**Comment by sumpfralle** [comment]
OK - I hope, nothing went wrong (since there were no objections). I will merge it now (#781).
