### ISSUE TITLE
dspam_ does not works when values are huge

### ISSUE THREAD

**Issue by jolan78** [munin-monitoring/contrib#828]
in: https://github.com/munin-monitoring/contrib/blob/master/plugins/dspam/dspam_#L237 
this line : 
`$dspam_stats -t -S | while read a b c d e f g h i j k l m x; do`
expect the output of dspam_stats to be space-separated, which is not the case when the values are huge. ex:

> virtualmail       TP:80312082 TN:198342928 FP: 82941 FN: 57326 SC:     0 NC:  3498

changing this line to : 
`IFS=' :'; $dspam_stats -t -S | while read a b c d e f g h i j k l m x; do`
fixes the problem

colons must then be removed when parsing.

here is what i changed :
[fix.txt](https://github.com/munin-monitoring/contrib/files/893539/fix.txt)

**Comment by sumpfralle** [comment]
Thank you for reporting this issue and even providing a fix!

Regarding your fix: I have one small nitpick. I guess, you should use the following style:
```
$dspam_stats -t -S | IFS=' :' while read a b c d e f g h i j k l m x; do
```
This will ensure that `IFS` is changed only for the `while` command and not for all following commands.

It would be great, if you could create a pull request with your changes. Would you need some directions for that?
Thank you again!

**Comment by jolan78** [comment]
here is the pull request : https://github.com/munin-monitoring/contrib/pull/830
please ignore https://github.com/munin-monitoring/contrib/issues/829

you are right about changing IFS for the whole script.
`IFS=' :' while read ...` did not work for me, but `while IFS=' :' read ...` did.
does it works for you ?

I modified the comments to reflect the possible lack of space separator.

regards.

**Comment by sumpfralle** [comment]
Great!

Regarding the position of the variable assignment: I was just guessing. Thank you for testing and fixing my assumption.

Regarding the two pull requests: you could have also force-pushed into your previous branch (amending your previous commits). Anyway - your approach was fine, too.

Thank you for fixing this issue!
