### ISSUE TITLE
dirsizes: please add support for customizing graph title

### ISSUE THREAD

**Issue by CyrilBrulebois** [munin-monitoring/contrib#839]
I have a few setups with different sets of directories, e.g. `dirsizes_home` and `dirsizes_srv`, but both graphs get the hardcoded `Directory sizes` title. It'd be nice to add support for a `graph_title` environment variable.

I've successfully tested [0001-dirsizes-add-support-for-env.graph_title.patch.txt](https://github.com/munin-monitoring/contrib/files/953767/0001-dirsizes-add-support-for-env.graph_title.patch.txt) with a slightly older version of the `dirsizes` plugin on munin 2.0.25 setups.

**Comment by dipohl** [comment]
You can do this with overwriting the plugin directive in Munin master configuration `munin.conf`

```
[cyril.example.org]
dirsizes_home.graph_title <your title>
dirsizes_srv.graph_title <your other title>
```
Please test and report the result.

**Comment by CyrilBrulebois** [comment]
Oh right, I didn't realize that. I guess I should read more about configuration before spending more time on tweaking plugins…

Works fine, closing. Thanks!

**Comment by dipohl** [comment]
Thanks for testing and feedback!

Concerning plugin configuration on Munin masters side start here:
http://guide.munin-monitoring.org/en/latest/reference/munin.conf.html#plugin-directives
Very useful is this technique for creating aggregate graphs:
http://guide.munin-monitoring.org/en/latest/example/graph/aggregate.html
http://guide.munin-monitoring.org/en/latest/example/graph/aggregated-stack.html
http://guide.munin-monitoring.org/en/latest/example/graph/aggregation-combined.html

Have fun with it! :-)

**Comment by CyrilBrulebois** [comment]
Many thanks for all the links! I might stick to my initial plan though, which is “reading all the docs is needed”. ;)
