### ISSUE TITLE
vmware esx_ plugin 

### ISSUE THREAD

**Issue by luntzel** [munin-monitoring/contrib#862]
concerning: "https://github.com/munin-monitoring/contrib/blob/master/plugins/vmware/esx_"

CentOS release 6.9
This is perl, v5.10.1
munin-server 2.0.33 
munin-node 2.0.33 

`munin-update` does not recognize it or list it in any log output; I cannot get it to come up in the node list UNLESS I run `cap multigraph`, then list remote1 like so:

```
[root@munin-server plugins]# nc munin-server 4949
# munin node at munin-server
nodes
munin-server
remote1
.
cap multigraph
cap multigraph dirtyconfig
list remote1
esx_remote1
fetch esx_remote1
{ ...lots of output }

```
What could I missing here? There are no magic markers. Hostnames seem to be correct and here's output from `munin-node-configure --debug`:

```
# Considering '/usr/share/munin/plugins/esx_'
#       Reading magic markers.
# Considering '/usr/share/munin/plugins/multips'
...
# Found 'esx_remote1'
...
esx_                       | yes  | remote1
```

And finally esx_ plugin-conf:

```
[esx_*]
timeout 60
env.user root
env.password SweetESXPasswordBro
#env.flatview top_level_entry
```

Any help here would be awesome. Love, Mark

**Comment by sumpfralle** [comment]
The `esx_` plugin uses the [multigraph feature](http://guide.munin-monitoring.org/en/latest/plugin/protocol-multigraph.html) and (correctly) calls `need_multigraph();` - thus the node will only expose it, if the requester announced the multigraph capability before.
But this was probably not your question?

Is your collecting server multigraph capable? (e.g. not older than v1.4)

is the plugin mentioned in the `munin-update.log` file on the collecting server?

**Comment by luntzel** [comment]
That's what is confusing to me - running 2.0.33. The plugin is not mentioned in the munin-update.log but I did see 'cap multigraph' was sent. My feeling now is that the collecting server does not know to ask for 'list remote1'

The stanza in munin.conf:

```
[munin-server]
    address 192.168.1.99
    use_node_name yes
```

I've played around with 'use_node_name no' which seems to have gotten 'remote1' added to the 'nodes' output. Yet the collecting server does not seem to know about it. I've added a section for 'remote1' (which is an esxi server) that does not have a munin-node installation and so it barfs. 

I can 'munin-run esx_remote1', I can 'fetch esx_remote1' and 'fetch esx_remote1 config' with nc and I encounter no problems. I'm probably missing something simple but wow am I stumped. Thanks for responding.

**Comment by niclan** [comment]
Hi,


On 20/07/17 18:57, Mark Luntzel wrote:
>
> That's what is confusing to me - running 2.0.33. The plugin is not 
> mentioned in the munin-update.log but I did see 'cap multigraph' was 
> sent. My feeling now is that the collecting server does not know to 
> ask for 'list remote1'
>

If you want munin to collect data for/from remote1 you must configurte it:

[remote1]
    address 1.2.3.4 (the server ip where the plugins for remote1 is 
available)
   use_node_name yes

If remote1 is probed from the server itself use 127.0.0.1 as address.

This is because munin only collects from the configured nodes, not all 
nodes available on all servers.  This is logical though I myself would 
also prefer that munin collects all available plugins for all available 
nodes on all the configured servers.

Nicolai

**Comment by sumpfralle** [comment]
How about dumping the full munin communication (on the host providing the plugin)?
```shell
tcpdump -npi eth0 -w traffic.dump port munin
```

Maybe you can see some details in something like "wireshark"? Otherwise I could I take a look.

**Comment by luntzel** [comment]
@niclan had the right idea - I ended up with 

```
[munin-server]
    address 127.0.0.1
[munin-server;remote1]
    address 127.0.0.1
```
for the remote esx machine in question. Along with the RRD diretory "fix" this plugin works great. Thanks @sumpfralle and @niclan so much. Cheers
