### ISSUE TITLE
PostgreSQL Transactions plugin

### ISSUE THREAD

**Issue by adekock11** [munin-monitoring/contrib#863]
When running the PostgreSQL Transactions plugin I get the following output:

```
root@master:/etc/munin/plugins# ./pg_transactions 
 \ncommits.value 278260525\nrollbacks.value 34093258
```

Notice that the new lines aren't properly rendered in the command line interface.

**Comment by sumpfralle** [comment]
Indead - this does not work.
Probably `psql` handled special characters more gently in older releases.

Would you prepare a pull request?

**Comment by adekock11** [comment]
@sumpfralle Alright thanks. Here it is: https://github.com/munin-monitoring/contrib/pull/865
