### ISSUE TITLE
munstrap tab id bug

### ISSUE THREAD

**Issue by pboesch** [munin-monitoring/contrib#884]
Hi,

Recently I've changed the default template by munstrap. The template works great except one behavior with tab. 

To reproduce:
- go to a nodeview and select a service tab for example #network
- go to homepage
- select a node service for example #service
- issue here: you will redirect to the last selected tab: #network 

Do you have an idea how to correct this ? Seems to correspond with **munstrap.min.js**.

Thanks for reply

**Comment by flob82** [comment]
Hi,

Same issue here, did you find a workaround ?

Thanks

**Comment by pboesch** [comment]
Hi,

Not yet...

**Comment by sumpfralle** [comment]
fixed by #912
