### ISSUE TITLE
ssl_ working as shell script, but not as plugin

### ISSUE THREAD

**Issue by oz42** [munin-monitoring/contrib#892]
The ssl_ plugin is not working:

2018/01/04-11:15:00 [9172] Error output from ssl_betsy.tuxfriends.net:
2018/01/04-11:15:00 [9172]      Can't exec "/usr/local/etc/munin/plugins/ssl_betsy.tuxfriends.net": No such file or directory at /usr/local/lib/perl5/site_perl/Munin/Node/Service.pm line 263, <STDIN> line 7.

When I run it as a shell skript the output is correct:

# bash /usr/local/etc/munin/plugins/ssl_betsy.tuxfriends.net
/usr/local/etc/munin/plugins/ssl_betsy.tuxfriends.net: line 29: /plugins/plugin.sh: No such file or directory
expire.value 60.0243

**Comment by sumpfralle** [comment]
It looks like the plugin cannot find the file `plugin.sh` - it is part of munin since around version 1.2, I think.

Or do you have an idea, why `MUNIN_LIBDIR` could be empty?

**Comment by niclan** [comment]
To get the MUNIN_* environment variables run the plugin under

``munin-run --servicedir $(pwd) ssl_betsy.tuxfriends.net``

optionaly add "config" at the end of the command.  This is how you need to run plugins to debug.
