### ISSUE TITLE
ssl_ not working on FreeBSD 11

### ISSUE THREAD

**Issue by oz42** [munin-monitoring/contrib#893]
The ssl_ plugin does not work with FreeBSD's awk version, so gawk from ports is needed.

Please include a check which awk to use like e.g.

gawk --version > /dev/null 2>&1 ; if [ ${?} -eq 0 ]; then AWK=$(which gawk); else AWK=$(which awk); fi

**Comment by sumpfralle** [comment]
Interesting!
Could I verify the broken behaviour with `awk --traditional`?

Or which specific gawk feature is missing here?

I would rather reduce the used set of features (and improve the testing scripts in this regard) instead of enforcing a specific implementation (if possible).

**Comment by oz42** [comment]
The system awk prints an error message: "awk: calling undefined function mktime"
