### ISSUE TITLE
plugin proftpd

### ISSUE THREAD

**Issue by stratege1401** [munin-monitoring/contrib#898]
Is it still maintained ??

/etc/munin/plugin-conf.d
[proftpd*]
group root

but nothing

**Comment by sumpfralle** [comment]
What exactly did you try and where did you encounter a result, that did not match your expectations?

**Comment by stratege1401** [comment]
using munin to check on proftpd users and traffic.

Added the plugin, did the [ln -s /usr/share/munin/plugins/proftpd /etc/munin/plugins/proftpd] restarted my node, and generated some connexions and traffic.

But the graph itself is not showing in my munin overview.

I have others plugins showing up like fai2ban or LVM_ event if they are empty.

For proftpd, nothing.

**Comment by sumpfralle** [comment]
Did you try to look at the [troubleshooting section of the munin guide](http://guide.munin-monitoring.org/en/latest/tutorial/troubleshooting.html#check-a-particular-plugin)?

Maybe try something along these lines:
```shell
# local test
munin-run proftpd
# connection test
echo "fetch proftpd" | nc localhost munin
```

Or maybe you want to take a look at the "update" log of the munin master (`/var/log/munin/munin-update.log` or similar).

**Comment by stratege1401** [comment]
Sorrrrrrry, found out the problem.

running munin-run proftpd , I received a # Unknown service 'proftpd'
so i went to check /usr/share/munin/plugins
The proftpd was in chmod 644 instead 755

Thank you for your help.

**Comment by sumpfralle** [comment]
I am glad, it works now!
