### ISSUE TITLE
kvm_net plugin not collecting and graphing any data

### ISSUE THREAD

**Issue by pack72** [munin-monitoring/contrib#916]
Hi,

I am running ubuntu xenial with kvm and the kvm_net plugin is not collecting and graphing any data.

cat /proc/net/dev shows the devices and traffic but the graph is empty,
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
 vnet9:       0       0    0    0    0     0          0         0    42936     257    0 15127183    0     0       0          0
ens2f1: 57124024236 74127530 2157   41    0  2157          0  10550012 25866919376 43275610    0    0    0     0       0          0
 vnet0: 21856380   86153    0    0    0     0          0         0 5791011317 15407990    0    0    0     0       0          0
 vnet8: 144230802  353318    0    0    0     0          0         0 1070797898 1244667    0    0    0     0       0          0
    lo: 3037355196 41044861    0    0    0     0          0         0 3037355196 41044861    0    0    0     0       0          0
ens2f2:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
 vnet7: 135682296624 18609633    0    0    0     0          0         0 49158069411 513736385    0  105    0     0       0          0
 vnet6: 8814895  118626    0    0    0     0          0         0 341288379  215957    0 12749603    0     0       0          0
ens2f3:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  eno2: 62916283485 194158875   18    6    0     0          0  14990419 42793861484 89371007    0    0    0     0       0          0
virbr0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
 vnet5: 383409687677 1591344810    0    0    0     0          0         0 419633147551 2118334045    0  560    0     0       0          0
 bond1: 1796453538060 5482725330   52 518664    0     0          0 528579724 6784827972639 6113418413    0    8    0     0       0          0
br-vlan: 36626853370 669643834    0 54343497    0     0          0         0     1008      12    0    0    0     0       0          0

![image](https://user-images.githubusercontent.com/17250458/39230842-581c5118-4868-11e8-838d-d3c0f6b9a025.png)

**Comment by sumpfralle** [comment]
I refreshed the plugin quite a bit, but I did not manage to find a reliable way of retrieving the network interface (in the virtualization host), that is attached to a specific VM.
I *guess*, that it worked before only for very specific setups.

Please check, whether it works for you now.

If not, then please read the documentation of the plugin (*Applicable Systems*) and report back, if you can find a way to determine the network interface on your system.
