### ISSUE TITLE
nginx_byprojects broken

### ISSUE THREAD

**Issue by Neraud** [munin-monitoring/contrib#922]
On my Debian Stretch host with perl v5.24.1, the error is : 

```
# munin-run nginx_byprojects_access
Odd number of elements in hash assignment at /etc/munin/plugins/nginx_byprojects_access line 41.
Use of uninitialized value within %ENV in list assignment at /etc/munin/plugins/nginx_byprojects_access line 41.
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /etc/munin/plugins/nginx_byprojects_access line 43.
```

Looking at the commit history, I see that there was a change in a836f07 : 
> "%ENV{foo}" does not work with older perl versions (e.g. v5.14).

After locally reverting this change, these plugins are working again for me.

**Comment by sumpfralle** [comment]
Indeed it looks that change was bad :(
I reverted it.

**Comment by sumpfralle** [comment]
Thank you!
