### ISSUE TITLE
bitcoind_ does not work with munin-node-configure

### ISSUE THREAD

**Issue by Talkless** [munin-monitoring/contrib#931]
Munin v2.0.33-1 on Debian Stretch.

`bitcoind_` plugin docummentation suggest:
https://github.com/munin-monitoring/contrib/blob/5a45d49760d74aa36b5c3bad112010beef01f502/plugins/currency/bitcoin/bitcoind_#L28

Meanwhile, my `/etc/munin/plugin-conf.d/bitcoind.conf`:
```
[bitcoind_*]
user bitcoin
```

As for `bitcoind_` plugin documentation, this should work as plugin would take RPC configuration from `$HOME/.bitcoin/bitcoin.conf` (as $HOME would be `bitcoin` user's home):
https://github.com/munin-monitoring/contrib/blob/5a45d49760d74aa36b5c3bad112010beef01f502/plugins/currency/bitcoin/bitcoind_#L13

But it `munin-node-configure` fails:
```
# Running 'autoconf' on bitcoind_
# Non-zero exit during autoconf (1)
# Junk printed to stderr
# Junk printed to stderr: Traceback (most recent call last):   File "./bitcoind_", line 241, in <module>     main()   File "./bitcoind_", line 89, in main     bitcoin_options.require('rpcuser', 'rpcpassword')   File "./bitcoind_", line 170, in require     ', '.join(missing))) ValueError: Missing required settings: rpcuser, rpcpassword.
```

It still needs `rpcuser` and `rpcpassword`. Looking at `strace` output it does not read `.bitcoin/bitcoin.conf` at all.

**Comment by Talkless** [comment]
It seems that this line:
https://github.com/munin-monitoring/contrib/blob/5a45d49760d74aa36b5c3bad112010beef01f502/plugins/currency/bitcoin/bitcoind_#L86

Produces path `/root/.bitcoin/bitcoin.conf`, NOT `/home/bitcoin/.bi...` so `munin-node-configure` ignores `/etc/munin/plugin-conf.d/bitcoin.conf` entry `user bitcoin` ?

How should plugin behave?

**Comment by Talkless** [comment]
Anyway, even avoiding issues with automated auth. info retrieval from `bitcoin.conf`, there's seems to be `RPC` issuestoo. Maybe this plugin is just too old, failing to talk to `bitcoind` daemon:
```
connect(3, {sa_family=AF_INET, sin_port=htons(8332), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
send(3, "POST / HTTP/1.1\r\nAccept-Encoding"..., 330, 0) = 330
recv(3, "HTTP/1.1 404 Not Found\r\nContent-"..., 8192, 0) = 604
```

**Comment by sumpfralle** [comment]
Somehow I jumped into *cleanup mode* and migrated the plugin to python3, as well as adding an explicit configuration file path (see #932).

Currently there is no simple way to determine the home directory of the currently effective user (see the fresh issue [#1054](https://github.com/munin-monitoring/munin/issues/1054)). Thus the explicit path is the best solution for now.

Regarding the change of the `RPC` interface: maybe it is really outdated - I cannot tell.

If you want to take a look how the current API behaves, I would be happy to assist you in turning this into a changeset for the plugin.

**Comment by sumpfralle** [comment]
I just merged my set of proposed cleanup changes (unrelated to your problem): #932.

Regarding the configuration file: please note, hat `munin-node` (and thus the plugins) are usually run via systemd with the setting `ProtectHome=yes` (see `man systemd.exec`). At least this is the case for the Debian packaging of munin. Thus your approach above (accessing the user's home directory) will not work (in a very hard to debug way) on such systems. Maybe you want to provide access credentials via environment variables instead or use a different configuration location (e.g. `/etc/bitcoind.conf`).

**Comment by Talkless** [comment]
@sumpfralle yes, my `bintcond.conf` is in `/etc`, and your commit `introduce explicit configuration file path ` should help (gonna try that).

Thanks for you work!

**Comment by sumpfralle** [comment]
Are there still open details or can we close the issue?

**Comment by Talkless** [comment]
Sorry, completely forgot this issue. I don't recall if I did anything w.r.t this issue, or what's the status is :/ .

**Comment by sumpfralle** [comment]
Thanks for your quick response!

The remaining issue is somehow, that the `$HOME` directory in the plugin context does not belong to the configured user. This is documented in #1054. Thus we can close this issue.
