### ISSUE TITLE
Doesnt show informations about client presence

### ISSUE THREAD

**Issue by herrwusel** [munin-monitoring/contrib#954]
As the title suggest I don't get information about the clients' presence. Using Prosody 0.10

**Comment by sumpfralle** [comment]
Which plugin do you refer to?

**Comment by herrwusel** [comment]
Sorry, I thought this was repository for the prosody_ plugin only. [This](https://github.com/munin-monitoring/contrib/tree/master/plugins/prosody) is the one I'm referring to.

**Comment by sumpfralle** [comment]
OK.

I am not a user of this plugin, thus maybe you can add more details?
E.g. what is the output of the following?
```shell
echo "c2s:show()" | nc localhost 5582
```

You may want to adjust the command above to your local setup and maybe filter out private data from the response (without breaking its formatting).

**Comment by herrwusel** [comment]
Thanks for trying to help me! This is what I got:

> examble.com
|    1@examble.com/Conversations.EkcJ [c2s3250520] available(0) (encrypted) (sm)
|    2@examble.com/dino.bce5456b [c2s1d83398] available(0) (encrypted) (sm)
|    3@examble.com/dino.ca9c01ff [c2s3ae2620] available(0) (encrypted) (sm)
|    3@examble.com/Conversations.-_cx [c2s3c78270] available(0) (encrypted) (sm)
|    4@examble.com/Conversations.eoX_ [c2s1d0ba80] available(0) (encrypted) (sm)
....
| OK: Total: 18 clients

**Comment by herrwusel** [comment]
I think I got it working for me. I changed
https://github.com/munin-monitoring/contrib/blob/c4d7d834abc410db9aeb9c055d54068eac6730d6/plugins/prosody/prosody_#L109

to 
`client_presence_re = re.compile("[\]] (.*?)\(\d+\)")`

I just read about regex and not sure if that is the proper way to do it. If you confirm it's alright I can do a pr.
