### ISSUE TITLE
 Zoom graphs not working in munstrap with apache server

### ISSUE THREAD

**Issue by sam42** [munin-monitoring/contrib#958]
I've installed munstrap as outlined and have it up an running but zoom in does not work properly... I am running apache (mpm event/cgid) with the following config:
Alias /munin/static /var/cache/munin/www/static
<Directory /var/cache/munin/www/static>
        Require local
        Options None
</Directory>

ScriptAlias /munin /usr/lib/munin/cgi/munin-cgi-html
<LocationMatch "^/munin/(?!static/)">
        Require local
        <IfModule mod_fcgid.c>
            SetHandler fcgid-script
        </IfModule>
        <IfModule !mod_fcgid.c>
            SetHandler cgi-script
        </IfModule>
</LocationMatch>

ScriptAlias /munin-cgi/munin-cgi-graph /usr/lib/munin/cgi/munin-cgi-graph
<Location /munin-cgi/munin-cgi-graph>
        Require local
        <IfModule mod_fcgid.c>
            SetHandler fcgid-script
        </IfModule>
        <IfModule !mod_fcgid.c>
            SetHandler cgi-script
        </IfModule>
</Location>

**Comment by variablenix** [comment]
I'm using munstrap version 2.0.26  and have Zoom working with Apache 2.4 and fcgid. What error message are you seeing in the logs? It's possible you may be running into a permissions issue. I updated a [wiki page](https://wiki.archlinux.org/index.php/Munin#DynaZoom_Permissions) with a solution to fix Zoom issues related to permissions.

>When Munin cannot draw graphs and logs a similar message to Could not draw graph "/var/lib/munin/cgi-tmp/munin-cgi-graph/" check to make sure group permissions are set on /var/lib/munin/cgi-tmp/munin-cgi-graph/ so the munin-cgi-graph directory has writeable group permissions such as drwxrwxr-x 3 munin http 4096 Aug 9 20:11 munin-cgi-graph.

>ls -l /var/lib/munin/cgi-tmp/

>If group permissions are not set, then

>chmod g+w /var/lib/munin/cgi-tmp/munin-cgi-graph/

So I believe once I changed the permissions of `/var/lib/munin/cgi-tmp/munin-cgi-graph/` to `775` and owned by the munin user and Apache group, in my case `http` - Munin finally created `/var/lib/munin/cgi-tmp/munin-cgi-graph/domain.tld/` and other sub-directories.

#### Apache
You may want to try adding a `RewriteRule` to specify the location for images. For example, here is my config that worked after fixing Zoom permissions.

```
<VirtualHost *:80>
   ServerName munin.domain.tld
   ServerAlias munin
   ServerAdmin  webmaster@domain.tld

   DocumentRoot /srv/http/munin

   ErrorLog /var/log/httpd/munin-error.log
   CustomLog /var/log/httpd/munin-access.log combined

   # Rewrites
   RewriteEngine On

   # Images
   RewriteRule ^/munin-cgi(.*) /usr/share/munin/cgi/$1 [L]

   # Ensure we can run (fast)cgi scripts
   <Directory "/usr/share/munin/cgi">
       Require all granted
       Options +ExecCGI
       <IfModule mod_fcgid.c>
           SetHandler fcgid-script
       </IfModule>
       <IfModule !mod_fcgid.c>
           SetHandler cgi-script
       </IfModule>
   </Directory>

</VirtualHost>
```
Hopefully this gives an idea how to fix Zoom in your own environment.

**Comment by sam42** [comment]
Hello,
my problem is solved. I think I was using the old repository https://github.com/jonnymccullagh/munstrap.

**Comment by sumpfralle** [comment]
Thank you for reporting your success!
