### ISSUE TITLE
prosody module fails in most cases

### ISSUE THREAD

**Issue by porrier** [munin-monitoring/contrib#981]
https://github.com/munin-monitoring/contrib/tree/master/plugins/prosody
```
# munin-run -d prosody_c2s
# Processing plugin configuration from /etc/opt/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /488/65534/
# Setting /egid/euid/ to /488 488/65534/
# Setting up environment
# Environment port = 4950
# Environment host = localhost
# About to run '/etc/opt/munin/plugins/prosody_c2s'
Traceback (most recent call last):
  File "/etc/opt/munin/plugins/prosody_c2s", line 181, in <module>
    main()
  File "/etc/opt/munin/plugins/prosody_c2s", line 63, in main
    secure_client_connections = int(parsed_info[0])
IndexError: list index out of range

# munin-run -d prosody_s2s
# Processing plugin configuration from /etc/opt/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /488/65534/
# Setting /egid/euid/ to /488 488/65534/
# Setting up environment
# Environment host = localhost
# Environment port = 4950
# About to run '/etc/opt/munin/plugins/prosody_s2s'
Traceback (most recent call last):
  File "/etc/opt/munin/plugins/prosody_s2s", line 181, in <module>
    main()
  File "/etc/opt/munin/plugins/prosody_s2s", line 91, in main
    print("outgoing_connections.value %s" % (parsed_info[0][0]))
IndexError: list index out of range

# munin-run -d prosody_uptime
# Processing plugin configuration from /etc/opt/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /488/65534/
# Setting /egid/euid/ to /488 488/65534/
# Setting up environment
# Environment port = 4950
# Environment host = localhost
# About to run '/etc/opt/munin/plugins/prosody_uptime'
Traceback (most recent call last):
  File "/etc/opt/munin/plugins/prosody_uptime", line 181, in <module>
    main()
  File "/etc/opt/munin/plugins/prosody_uptime", line 143, in main
    + float(parsed_info[2])/60/24)
IndexError: list index out of range

# munin-run -d prosody_presence
# Processing plugin configuration from /etc/opt/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /488/65534/
# Setting /egid/euid/ to /488 488/65534/
# Setting up environment
# Environment port = 4950
# Environment host = localhost
# About to run '/etc/opt/munin/plugins/prosody_presence'
available.value 0
chat.value 0
away.value 0
xa.value 0
dnd.value 0
```
The only one I get data from is prosody_users

**Comment by sumpfralle** [comment]
Thank you for reporting the issue!

Could please share the output of the following commands:
```shell
printf 's2s:show()\nquit\n' | nc localhost 5582
printf 'c2s:show_secure()\nquit\n' | nc localhost 5582
printf 'c2s:show_insecure()\nquit\n' | nc localhost 5582
printf 'c2s:show()\nquit\n' | nc localhost 5582
printf 'server:uptime()\nquit\n' | nc localhost 5582
```

You need "netcat" for the above commands. Probably "telnet" works, as well.

Thank you!

**Comment by porrier** [comment]
Hello!

Lars Kruse <notifications@github.com> schrieb am 11.05.19 um 05:15:23 Uhr:

> Thank you for reporting the issue!
> 
> Could please share the output of the following commands:
> ```shell
> printf 's2s:show()\nquit\n' | nc localhost 5582

| bitcorner.de
|  <- conference.prosody.im [s2sin20d94f0] (authenticated) (encrypted) (IPv6)
|  -> nimmini.de [s2sout1ef8d10] (authenticated) (encrypted) (IPv6)
| OK: Total: 1 outgoing, 1 incoming connections

> printf 'c2s:show_secure()\nquit\n' | nc localhost 5582

contains sensible data but the output shows correct values.

> printf 'c2s:show_insecure()\nquit\n' | nc localhost 5582

| OK: Total: 0 insecure client connections

> printf 'c2s:show()\nquit\n' | nc localhost 5582

contains sensible data but the output shows correct values.

> printf 'server:uptime()\nquit\n' | nc localhost 5582

| OK: This server has been running for 0 days, 2 hours and 48 minutes (since Sat May 11 11:51:55 2019)

> ```
> 
> You need "netcat" for the above commands. Probably "telnet" works, as well.
> 
> Thank you!
> 

Andreas

-- 
PGP-Fingerprint: D392 5D21 0299 63D7 5BAE 4562 1E56 B2EA 81A2 59F1

**Comment by sumpfralle** [comment]
Thank you for your feedback!

The output of `s2s:show()` looks reasonable to me. I tried to simulate the parsing manually and did not encounter a problem. Weird.

I could not check the other commands, since you did not share its output (with obfuscated private details) :)

I am slightly lost here, since I have no prosody server around (I am using ejabberd). Thus I am afraid, that you will need to add some `print` statements at the appropriate locations (just before the line that caused the stracktraces above) in order find the issue.

For example you could add the following before line 91:
```python
print(telnet_response)
print()
print(parsed_info)
```

This should show exactly, what went wrong during parsing.

**Comment by porrier** [comment]
Hello!

Responding a bit late, just noticed there was an answer.

With print(parsed_info) on line 91 I get:
# munin-run -d prosody_s2s
# Processing plugin configuration from /etc/opt/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /488/65534/
# Setting /egid/euid/ to /488 488/65534/
# Setting up environment
# Environment port = 4950
# Environment host = localhost
# About to run '/etc/opt/munin/plugins/prosody_s2s'
[]
Traceback (most recent call last):
  File "/etc/opt/munin/plugins/prosody_s2s", line 182, in <module>
    main()
  File "/etc/opt/munin/plugins/prosody_s2s", line 92, in main
    print("outgoing_connections.value %s" % (parsed_info[0][0]))
IndexError: list index out of range

I am clueless here.

**Comment by sumpfralle** [comment]
@porrier: thank you!

Sadly the most interesting detail can only be found in `telnet_response` (I mentioned it above).
Could you please add another line with `print(telnet_response)` before line 91?

**Comment by sumpfralle** [comment]
The above output is weird:
* previously the output (`[]`) followed immediately after `About to run '/etc/opt/munin/plugins/prosody_s2s'`
* now there are two more lines (`munin node at localhost` and `Unknown command.`). The latter is definitely not output from the plugin. This is confusing.

Regarding the new "print" line in the plugin: the crucial line number in the stacktrace did not change (still at 92). Thus you probably replaced the other `print` line with the new one? Maybe you want to share the current state of your plugin via some paste service? Thank you!

**Comment by porrier** [comment]
Yes I changed the line 91 from print(parsed_info) to print(telnet_response).
Now I have both on line 91 and 92 and get:

# munin-run -d prosody_s2s
# Processing plugin configuration from /etc/opt/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /488/65534/
# Setting /egid/euid/ to /488 488/65534/
# Setting up environment
# Environment port = 4950
# Environment host = localhost
# About to run '/etc/opt/munin/plugins/prosody_s2s'
[]
# munin node at localhost
# Unknown command.

Traceback (most recent call last):
  File "/etc/opt/munin/plugins/prosody_s2s", line 183, in <module>
    main()
  File "/etc/opt/munin/plugins/prosody_s2s", line 93, in main
    print("outgoing_connections.value %s" % (parsed_info[0][0]))
IndexError: list index out of range

I pasted the mod at http://dpaste.com/14TYWAA

**Comment by sumpfralle** [comment]
Thank you!

Now the output is indeed easier to understand.
Indeed the above looks like the `prosody_s2s` plugin connects to a *munin-node* service? This is certainly not correct. Are you sure, that you configured the right port for the prosody_s2s plugin? Probably it should be 5582 (a prosody server).
Maybe verify, which process handles that port? (`netstat -lpn | grep CONFIGURED_PORT`)

**Comment by porrier** [comment]
I am confused. The readme states:

`mod_munin` listens on port `4949` on all local interfaces by default.
This can be changed with the standard [port and network configuration][doc:ports]:
munin_ports = { 4949 }
If you already have a `munin-node` instance running, you can set a different port to avoid the conflict.

So I set port 4950 to avoid the conflict with munin-node. If I set port 4949 the module munin refuses to load because munin-node is listening on that port.

**Comment by porrier** [comment]
tcp        0      0 :::4949                 :::*                    LISTEN      10762/perl
tcp        0      0 0.0.0.0:4950            0.0.0.0:*               LISTEN      7994/lua           
tcp        0      0 :::4950                 :::*                    LISTEN      7994/lua

**Comment by porrier** [comment]
Seems I found the culprit. I had set
[prosody_*]
env.host localhost
env.port 4950
user prosody
group prosody

Commenting out env.port 4950 solved the problem.

# munin-run -d prosody_s2s
# Processing plugin configuration from /etc/opt/munin/plugin-conf.d/munin-node
# Setting /rgid/ruid/ to /488/1009/
# Setting /egid/euid/ to /488 488 1000/1009/
# Setting up environment
# Environment host = localhost
# About to run '/etc/opt/munin/plugins/prosody_s2s'
[('1', '0')]
|                    ____                \   /     _
                    |  _ \ _ __ ___  ___  _-_   __| |_   _
                    | |_) | '__/ _ \/ __|/ _ \ / _` | | | |
                    |  __/| | | (_) \__ \ |_| | (_| | |_| |
                    |_|   |_|  \___/|___/\___/ \__,_|\__, |
                    A study in simplicity            |___/


| Welcome to the Prosody administration console. For a list of commands, type: help
| You may find more help on using this console in our online documentation at 
| https://prosody.im/doc/console

| bitcorner.de
|  -> nimmini.de [s2sout16526f0] (authenticated) (encrypted) (IPv6)
| OK: Total: 1 outgoing, 0 incoming connections
outgoing_connections.value 1
incoming_connections.value 0

**Comment by sumpfralle** [comment]
Great!

Thus everything works (after removing the `print` statements, that you added for debugging)?

**Comment by porrier** [comment]
Yes, all graphs are working fine now. Thank you for the help!
