### ISSUE TITLE
bash not working in plugin like it does in shell script

### ISSUE THREAD

**Issue by Sir-Will** [munin-monitoring/contrib#989]
I have the following script which is working fine in a .sh file but not in a munin plugin.

In the munin plugin it results in
```
declare -A arr=([" S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT   "]="49664.0 51200.0 37520.3  0.0   1991680.0 523106.0 4194304.0  2531007.6  419136.0 399212.1 80000.0 74782.9   2451   47.106   8      3.869   50.975" )
```
While in the shell script it does result in
```
declare -A arr=([OU]="1732418.8" [S1C]="41984.0" [S0U]="0.0" [YGC]="997" [S0C]="52224.0" [S1U]="41505.0" [OC]="2463232.0" [GCT]="12.720" [EU]="265935.3" [FGCT]="1.951" [EC]="1996288.0" [YGCT]="10.769" [MU]="240137.5" [CCSC]="42264.0" [FGC]="6" [CCSU]="40514.8" [MC]="248344.0" )
```

The script:
```bash
#!/bin/bash
proc=" S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT     GCT
#38912.0 38912.0  0.0   24562.0 2017280.0 1983122.4 2463232.0  1663816.6  247448.0 239411.0 42136.0 40412.6    947   10.216   6      1.951   12.167"

declare -A arr=();
{ read -ra keys; read -ra values; } <<< "$proc"
for (( i = 0; i < ${#keys[@]}; i++ )); do
    arr[${keys[i]}]=${values[i]};
done

declare -p arr
echo ${arr[S1C]}
```

**Comment by sumpfralle** [comment]
The only differences between direct execution of the script and having it executed by munin (e.g. via `munin-run YOUR_PLUGIN`) should be the following ones:
* different user
* reduced set of environment variables
* minimal `PATH` variable
* some systemd-based hardening features may be in effect (e.g. a private `/tmp` directory) - see the systemd service file of `munin-node` for details

`munin-node` does not try to be smart about plugins (e.g. parsing their structure), thus you can rest assured, that the file is simply executed with the given shebang.

Thus if you see a difference between direct execution and the execution via munin, then I can only suggest to try to minimize the different between both environments (e.g. run the script as the user `munin`). Debugging via `set -x` or (as a last resort) via `strace` could also help.

**Comment by Sir-Will** [comment]
If the plugin is configured as `user root` in the node config then it executes it as root user, right?
How would I use `set -x`?

**Comment by sumpfralle** [comment]
> If the plugin is configured as user root in the node config then it executes it as root user, right?

Correct.

> How would I use set -x?

`set -x` is a bash (or rather: shell) builtin command.

**Comment by Sir-Will** [comment]
Found the issue, I changed `IFS` in the script without noticing, my bad.
Thanks for your help though.

**Comment by sumpfralle** [comment]
You are welcome!
